
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '67D196765C6411A86912751487B71A83'
    
_lr_action_items = {'JAVASCRIPT':([0,1,2,3,4,5,15,16,24,],[3,-5,3,-14,-3,-4,-8,3,-9,]),'STRING':([0,1,2,3,4,5,15,16,17,24,],[1,-5,1,-14,-3,-4,-8,1,19,-9,]),'WORD':([0,1,2,3,4,5,7,9,10,11,15,16,17,19,20,21,24,],[4,-5,4,-14,-3,-4,9,-6,13,13,-8,4,20,-13,-12,23,-9,]),'LANGLE':([0,1,2,3,4,5,15,16,24,],[7,-5,7,-14,-3,-4,-8,7,-9,]),'EQUAL':([0,1,2,3,4,5,13,15,16,24,],[5,-5,5,-14,-3,-4,17,-8,5,-9,]),'SLASHRANGLE':([9,10,11,12,14,19,20,],[-6,-11,-11,15,-10,-13,-12,]),'$end':([0,1,2,3,4,5,6,8,15,24,],[-2,-5,-2,-14,-3,-4,0,-1,-8,-9,]),'RANGLE':([9,10,11,12,14,19,20,22,23,],[-6,-11,-11,16,-10,-13,-12,24,-7,]),'LANGLESLASH':([1,2,3,4,5,8,15,16,18,24,],[-5,-2,-14,-3,-4,-1,-8,-2,21,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'element':([0,2,16,],[2,2,2,]),'tagnameend':([21,],[22,]),'tag_argument':([10,11,],[11,11,]),'tagname':([7,],[10,]),'tag_arguments':([10,11,],[12,14,]),'html':([0,2,16,],[6,8,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html","S'",1,None,None,None),
  ('html -> element html','html',2,'p_html','htmlgrammar.py',9),
  ('html -> <empty>','html',0,'p_html_empty','htmlgrammar.py',13),
  ('element -> WORD','element',1,'p_element_word','htmlgrammar.py',17),
  ('element -> EQUAL','element',1,'p_element_word_eq','htmlgrammar.py',21),
  ('element -> STRING','element',1,'p_element_word_string','htmlgrammar.py',25),
  ('tagname -> WORD','tagname',1,'p_tagname','htmlgrammar.py',30),
  ('tagnameend -> WORD','tagnameend',1,'p_tagnameend','htmlgrammar.py',36),
  ('element -> LANGLE tagname tag_arguments SLASHRANGLE','element',4,'p_element_tag_emtpy','htmlgrammar.py',47),
  ('element -> LANGLE tagname tag_arguments RANGLE html LANGLESLASH tagnameend RANGLE','element',8,'p_element_tag','htmlgrammar.py',54),
  ('tag_arguments -> tag_argument tag_arguments','tag_arguments',2,'p_tag_arguments','htmlgrammar.py',59),
  ('tag_arguments -> <empty>','tag_arguments',0,'p_tag_arguments_empty','htmlgrammar.py',64),
  ('tag_argument -> WORD EQUAL WORD','tag_argument',3,'p_tag_argument_word','htmlgrammar.py',68),
  ('tag_argument -> WORD EQUAL STRING','tag_argument',3,'p_tag_argument_string','htmlgrammar.py',72),
  ('element -> JAVASCRIPT','element',1,'p_element_javascript','htmlgrammar.py',76),
]
